// Generated by CoffeeScript 1.6.3
require('../vertex')({
  listen: {
    port: 3001
  },
  api: {
    listen: {
      port: 3000
    },
    allowRoot: true,
    root: {}
  },
  log: {
    level: 'debug'
  }
});
