// Generated by CoffeeScript 1.6.3
var server;

server = require('../api/server')({
  api: {
    listen: {
      port: 3000
    }
  }
});

server.listen(function(address) {
  return console.log(address);
});
