// Generated by CoffeeScript 1.6.3
var server;

server = require('../api/server')({
  http: {
    listen: {
      port: 3000
    }
  }
}, function(req, res) {
  res.writeHead(200);
  return res.end('...........');
});

server.listen(function(error, address) {
  return console.log(address);
});
