// Generated by CoffeeScript 1.6.3
var Kitten, kittySchema, mongoose;

mongoose = require('mongoose').connect('mongodb://localhost/test');

kittySchema = mongoose.Schema({
  name: String
});

Kitten = mongoose.model('Kitten', kittySchema);
