// Generated by CoffeeScript 1.6.3
var Kitten, kittySchema, mongoose, routes;

mongoose = require('mongoose').connect('mongodb://localhost/test');

kittySchema = mongoose.Schema({
  name: {
    type: String,
    index: {
      unique: true
    }
  }
});

Kitten = mongoose.model('Kitten', kittySchema);

require('../vertex')({
  http: {
    listen: {
      port: 3000
    }
  },
  root: routes = {
    kittens: function(_arg, callback) {
      var body, kitten, method;
      method = _arg.method, body = _arg.body;
      switch (method) {
        case 'POST':
          return (kitten = new Kitten(body)).save(function(err) {
            if (err != null) {
              return callback(null, {
                statusCode: 409,
                error: err
              });
            }
            return callback(null, kitten);
          });
      }
    }
  }
});

routes.kittens.$api = {};
