// Generated by CoffeeScript 1.6.3
var lastInstance;

lastInstance = void 0;

module.exports._test = function() {
  return lastInstance;
};

module.exports.create = function(config) {
  var api, local;
  lastInstance = local = {
    root: config.root,
    handle: function(req, res) {
      res.writeHead(200);
      return res.end('...........');
    }
  };
  return api = {
    handle: local.handle
  };
};
