// Generated by CoffeeScript 1.6.3
var lastInstance;

lastInstance = void 0;

module.exports._test = function() {
  return lastInstance;
};

module.exports.create = function(config) {
  var api, local;
  lastInstance = local = {
    root: config.root,
    handle: function(req, res) {
      if (config.allowRoot) {
        res.writeHead(200);
        res.write(JSON.stringify(local.root));
        return res.end();
      }
      res.writeHead(404);
      return res.end();
    }
  };
  return api = {
    handle: local.handle
  };
};
