// Generated by CoffeeScript 1.6.3
var deferred;

deferred = require('also').deferred;

module.exports.create = function(config) {
  var local;
  return local = {
    process: deferred(function(action, opts) {
      var path;
      path = opts.path.split('/').filter(function(p) {
        return p.length > 0;
      });
      return local.recurse(opts, path, config.root, function(error, result) {
        if (error != null) {
          return action.reject(error);
        }
        return action.resolve(result);
      });
    }),
    recurse: function(opts, path, object, callback) {
      var error, run;
      try {
        run = function() {
          var nextKey;
          if (nextKey = path.shift()) {
            if (!(object = object[nextKey])) {
              return callback(null, {
                statusCode: 404
              });
            }
            return local.recurse(opts, path, object, callback);
          } else {
            return callback(null, {
              statusCode: 200,
              body: object
            });
          }
        };
        if (typeof object === 'function') {
          if (!object.$api) {
            return callback(null, {
              statusCode: 404
            });
          }
          opts.rest = path;
          return object(opts, function(error, result) {
            object = result;
            return run();
          });
        } else {
          return run();
        }
      } catch (_error) {
        error = _error;
        return callback(error);
      }
    }
  };
};
