// Generated by CoffeeScript 1.6.3
var deferred;

deferred = require('also').deferred;

module.exports.create = function(config) {
  var local;
  return local = {
    process: deferred(function(action, opts) {
      var path;
      path = opts.path.split('/').filter(function(p) {
        return p.length > 0;
      });
      return local.recurse(opts, path, null, function(error, result) {
        return action.resolve(result);
      });
    }),
    recurse: function(opts, path, result, callback) {
      return callback(null, {
        body: config.root
      });
    }
  };
};
