// Generated by CoffeeScript 1.6.3
var lastInstance;

lastInstance = void 0;

module.exports.create = function(config) {
  var api, local;
  lastInstance = local = {
    process: function() {},
    recurse: function() {}
  };
  return api = {
    process: local.process
  };
};

module.exports._test = function() {
  return lastInstance;
};
