// Generated by CoffeeScript 1.6.3
var http;

http = require('http');

module.exports = function(config) {
  var local;
  if (config == null) {
    config = {};
  }
  return local = {
    server: void 0,
    listen: function(callback) {
      var hostname, opts, port;
      if (!(function() {
        try {
          return opts = config.api.listen;
        } catch (_error) {}
      })()) {
        return;
      }
      port = parseInt(opts.port);
      hostname = opts.hostname;
      local.server = http.createServer();
      return local.server.listen(port, hostname, function() {
        return callback(null, local.server.address());
      });
    },
    close: function() {
      try {
        return local.server.close();
      } catch (_error) {}
    }
  };
};
