// Generated by CoffeeScript 1.6.3
var http;

http = require('http');

module.exports.server = function(config) {
  var opts, port, server;
  if (config == null) {
    config = {};
  }
  if (!(opts = config.api != null)) {
    return;
  }
  port = parseInt(config.api.port);
  server = http.createServer();
  return server.listen(port);
};
