// Generated by CoffeeScript 1.6.3
var http;

http = require('http');

module.exports = function(config, handler) {
  var local;
  return local = {
    server: void 0,
    listen: function(callback) {
      var hostname, listenArgs, port;
      if (!(function() {
        try {
          return listenArgs = config.http.listen;
        } catch (_error) {}
      })()) {
        return;
      }
      port = parseInt(listenArgs.port);
      hostname = listenArgs.hostname;
      local.server = http.createServer(handler);
      return local.server.listen(port, hostname, function() {
        return callback(null, local.server.address());
      });
    },
    close: function() {
      try {
        return local.server.close();
      } catch (_error) {}
    }
  };
};
