// Generated by CoffeeScript 1.6.3
var Bunyan, basename;

basename = require('path').basename;

Bunyan = require('bunyan');

module.exports.create = function(config) {
  if (config == null) {
    config = {};
  }
  return Bunyan.createLogger({
    name: config.title || basename(process.argv[1]).split('.').shift(),
    level: ((function() {
      try {
        return config.log.level;
      } catch (_error) {}
    })()) || 'info',
    serializers: {
      socket: function(socket) {
        return {
          id: socket.id,
          readyState: socket.transport.readyState,
          request: socket.request.url
        };
      }
    }
  });
};
