// Generated by CoffeeScript 1.6.3
var Bunyan, basename;

basename = require('path').basename;

Bunyan = require('bunyan');

module.exports.create = function(config) {
  var name;
  name = config.title || basename(process.argv[1]).split('.').shift();
  return Bunyan.createLogger({
    name: name
  });
};
