// Generated by CoffeeScript 1.6.3
var Client;

Client = require('engine.io-client');

module.exports = function(config) {
  var local;
  return local = {
    client: void 0,
    connect: function() {
      return local.client = new Client.Socket(config.connect.uri);
    },
    close: function() {}
  };
};
