// Generated by CoffeeScript 1.6.3
var Client;

Client = require('engine.io-client');

module.exports = function(config) {
  var local;
  return local = {
    socket: void 0,
    connect: function() {
      if (local.socket != null) {
        return local.reconnect();
      }
      return local.socket || (local.socket = new Client.Socket(config.connect.uri));
    },
    close: function() {}
  };
};
