module.exports = {

  CLUSTER_ROUTE_CODE: 1,
  CLUSTER_HANDLER_JOIN_1: 1,
  CLUSTER_HANDLER_JOIN_2: 2,
  CLUSTER_HANDLER_JOIN_3: 3,
  CLUSTER_HANDLER_JOIN_4: 4,
  CLUSTER_HANDLER_SYNC_1: 5,
  CLUSTER_HANDLER_SYNC_2: 6,
  CLUSTER_HANDLER_SYNC_3: 7,
  CLUSTER_HANDLER_STORE_1: 8,
  CLUSTER_HANDLER_STORE_2: 9,
  CLUSTER_HANDLER_STORE_3: 10,
  CLUSTER_HANDLER_STORE_4: 11
};
