// Generated by CoffeeScript 1.6.3
var routes;

routes = {
  module: {
    "function": function(opts, callback) {
      console.log(opts);
      return callback(null, {});
    }
  }
};

routes.module["function"].$www = {};

require('./vertex')({
  www: {
    root: routes,
    listen: {
      port: 3000
    }
  }
});
