// Generated by CoffeeScript 1.6.3
var routes;

routes = {
  module: {
    "function": function(opts, callback) {
      console.log(opts);
      return callback(null, {});
    },
    broken: function(opts, callback) {
      return callback(new Error('Moo'));
    }
  }
};

routes.module["function"].$www = {};

routes.module.broken.$www = {};

require('./vertex').create.www({
  routes: routes
});
