// Generated by CoffeeScript 1.6.3
var Api, Hub, Logger, parallel, v4;

v4 = require('node-uuid').v4;

parallel = require('also').parallel;

Api = require('./api/api');

Hub = require('./hub/hub');

Logger = require('./logger/logger');

module.exports = function(config) {
  var log, title, uuid;
  title = config.title || 'Untitled Vertex';
  uuid = config.uuid || v4();
  log = Logger.create(config);
  return parallel([
    function() {
      if (config.api != null) {
        return Api.create(config, log).listen();
      }
    }, function() {
      if (config.listen != null) {
        return Hub.create(config, log).listen();
      }
    }
  ]).then(function(_arg) {
    var api, hub;
    api = _arg[0], hub = _arg[1];
    if (api != null) {
      log.info({
        listen: api.server.address()
      }, 'api listening');
    }
    if (hub != null) {
      return log.info({
        listen: hub.transport.address()
      }, 'hub listening');
    }
  }, function(error) {
    log.fatal(error);
    return process.exit(1);
  });
};

module.exports.Client = require('./client/client');
