// Generated by CoffeeScript 1.6.3
var Http, Hub, parallel, v4;

v4 = require('node-uuid').v4;

parallel = require('also').parallel;

Http = require('./www/http');

Hub = require('./hub/hub');

module.exports.create = function(config) {
  var title, uuid;
  title = config.title || 'Untitled Vertex';
  uuid = config.uuid || v4();
  return parallel([
    function() {
      if (config.www != null) {
        return Http.create(config).listen();
      }
    }, function() {
      if (config.listen != null) {
        return Hub.create(config).listen();
      }
    }
  ]).then(function(_arg) {
    var hub, www;
    www = _arg[0], hub = _arg[1];
  }, function(error) {
    console.log(error.stack);
    return process.exit(1);
  });
};
