// Generated by CoffeeScript 1.6.3
var Api, Logger, v4;

v4 = require('node-uuid').v4;

Api = require('./api/api');

Logger = require('./logger/logger');

module.exports = function(config) {
  var log, title, uuid;
  title = config.title || 'Untitled Vertex';
  uuid = config.uuid || v4();
  log = Logger.create(config);
  return Api.create(config, log).listen(function(err, api) {
    if (err != null) {
      log.fatal(err);
      return process.exit(1);
    }
  });
};
