// Generated by CoffeeScript 1.6.3
var engine;

engine = require('engine.io');

module.exports = function(config) {
  var local;
  return local = {
    server: void 0,
    listen: function() {
      var server;
      local.server = server = engine.listen(config.listen.port);
      return server.on('connection', function(socket) {
        return console.log({
          connected: socket.id
        });
      });
    },
    close: function() {}
  };
};
