// Generated by CoffeeScript 1.6.3
var VERSION, engine;

VERSION = 1;

engine = require('engine.io');

module.exports = function(config) {
  var local;
  return local = {
    server: void 0,
    clients: {},
    timestamp: function() {
      return new Date;
    },
    listen: function() {
      var server;
      local.server = server = engine.listen(config.listen.port);
      return server.on('connection', function(socket) {
        local.clients[socket.id] = {
          status: {
            value: 'connecting',
            at: local.timestamp()
          },
          socket: socket
        };
        return socket.on('message', function(payload) {
          var data, event, version, _ref;
          version = payload[0];
          _ref = JSON.parse(payload.slice(1)), event = _ref.event, data = _ref.data;
          return local[event](socket, data);
        });
      });
    },
    handshake: function(socket, data) {
      var secret;
      secret = data.secret;
      if (secret !== config.secret) {
        return socket.send(VERSION + '{"event":"reject"}');
      }
      return socket.send(VERSION + '{"event":"accept"}');
    },
    close: function() {}
  };
};
